-- Biggie writes immutable scrape snapshots here. The trigger below only emits an
-- event when the newest snapshot changes the price for the same competitor/item.
create table if not exists public.biggie_price_history (
  id bigint generated by default as identity primary key,
  competitor_name text not null check (char_length(trim(competitor_name)) between 1 and 160),
  item_name text not null check (char_length(trim(item_name)) between 1 and 160),
  price numeric(12, 2) not null check (price >= 0),
  currency text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  source_url text,
  scraped_at timestamptz not null default now(),
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

comment on table public.biggie_price_history is
  'Append-only competitor price snapshots populated by Biggie.';

create index if not exists biggie_price_history_lookup_idx
  on public.biggie_price_history (
    competitor_name,
    item_name,
    scraped_at desc,
    id desc
  );

alter table public.biggie_price_history enable row level security;
revoke all on table public.biggie_price_history from anon, authenticated;
grant select, insert on table public.biggie_price_history to service_role;
grant usage, select on sequence public.biggie_price_history_id_seq to service_role;

create table if not exists public.competitor_price_change_events (
  id bigint generated by default as identity primary key,
  source_history_id bigint not null unique
    references public.biggie_price_history(id) on delete cascade,
  competitor_name text not null,
  item_name text not null,
  old_price numeric(12, 2) not null,
  new_price numeric(12, 2) not null,
  currency text not null,
  direction text not null check (direction in ('increased', 'decreased')),
  change_amount numeric(12, 2) not null,
  change_percent numeric(12, 2),
  source_url text,
  observed_at timestamptz not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'delivered', 'failed')),
  attempts smallint not null default 0 check (attempts between 0 and 3),
  processing_started_at timestamptz,
  recommendation text,
  ai_model text,
  last_error text,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.competitor_price_change_events is
  'Durable queue of actual competitor price changes enriched once by AI and broadcast to SSE clients.';

create index if not exists competitor_price_change_events_stream_idx
  on public.competitor_price_change_events (id, status);

alter table public.competitor_price_change_events enable row level security;
revoke all on table public.competitor_price_change_events from anon, authenticated;
grant select, update on table public.competitor_price_change_events to service_role;
grant usage, select on sequence public.competitor_price_change_events_id_seq to service_role;

create or replace function public.detect_biggie_price_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_snapshot public.biggie_price_history%rowtype;
begin
  -- Ignore a late/backfilled row: only the newest snapshot can produce a live event.
  if exists (
    select 1
    from public.biggie_price_history as newer
    where newer.competitor_name = new.competitor_name
      and newer.item_name = new.item_name
      and (newer.scraped_at, newer.id) > (new.scraped_at, new.id)
  ) then
    return new;
  end if;

  select previous.*
    into previous_snapshot
  from public.biggie_price_history as previous
  where previous.competitor_name = new.competitor_name
    and previous.item_name = new.item_name
    and (previous.scraped_at, previous.id) < (new.scraped_at, new.id)
  order by previous.scraped_at desc, previous.id desc
  limit 1;

  -- First observation and unchanged observations intentionally stay quiet.
  if previous_snapshot.id is null or previous_snapshot.price = new.price then
    return new;
  end if;

  insert into public.competitor_price_change_events (
    source_history_id,
    competitor_name,
    item_name,
    old_price,
    new_price,
    currency,
    direction,
    change_amount,
    change_percent,
    source_url,
    observed_at
  )
  values (
    new.id,
    new.competitor_name,
    new.item_name,
    previous_snapshot.price,
    new.price,
    new.currency,
    case when new.price > previous_snapshot.price then 'increased' else 'decreased' end,
    new.price - previous_snapshot.price,
    round(((new.price - previous_snapshot.price) / nullif(previous_snapshot.price, 0)) * 100, 2),
    new.source_url,
    new.scraped_at
  )
  on conflict (source_history_id) do nothing;

  return new;
end;
$$;

drop trigger if exists detect_biggie_price_change_after_insert
  on public.biggie_price_history;

create trigger detect_biggie_price_change_after_insert
after insert on public.biggie_price_history
for each row execute function public.detect_biggie_price_change();

-- Atomically returns the next event for a client. Exactly one client claims AI
-- work; every client can read the stored recommendation once it is ready.
create or replace function public.claim_price_change_event(
  p_after_id bigint default 0
)
returns table (
  id bigint,
  competitor_name text,
  item_name text,
  old_price numeric,
  new_price numeric,
  currency text,
  direction text,
  change_amount numeric,
  change_percent numeric,
  source_url text,
  observed_at timestamptz,
  recommendation text,
  ai_model text,
  claimed boolean
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  event_row public.competitor_price_change_events%rowtype;
  did_claim boolean := false;
begin
  select event.*
    into event_row
  from public.competitor_price_change_events as event
  where event.id > greatest(p_after_id, 0)
    and (event.recommendation is not null or event.attempts < 3)
  order by event.id
  limit 1
  for update;

  if event_row.id is null then
    return;
  end if;

  if event_row.recommendation is null
    and event_row.attempts < 3
    and (
      event_row.status in ('pending', 'failed')
      or (
        event_row.status = 'processing'
        and event_row.processing_started_at < now() - interval '30 seconds'
      )
    )
  then
    update public.competitor_price_change_events as event
    set status = 'processing',
        attempts = event.attempts + 1,
        processing_started_at = now(),
        last_error = null,
        updated_at = now()
    where event.id = event_row.id
    returning event.* into event_row;
    did_claim := true;
  end if;

  return query select
    event_row.id,
    event_row.competitor_name,
    event_row.item_name,
    event_row.old_price,
    event_row.new_price,
    event_row.currency,
    event_row.direction,
    event_row.change_amount,
    event_row.change_percent,
    event_row.source_url,
    event_row.observed_at,
    event_row.recommendation,
    event_row.ai_model,
    did_claim;
end;
$$;

create or replace function public.complete_price_change_event(
  p_event_id bigint,
  p_recommendation text,
  p_ai_model text
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.competitor_price_change_events
  set status = 'delivered',
      recommendation = p_recommendation,
      ai_model = p_ai_model,
      delivered_at = now(),
      updated_at = now(),
      last_error = null
  where id = p_event_id;
$$;

create or replace function public.fail_price_change_event(
  p_event_id bigint,
  p_error text
)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.competitor_price_change_events
  set status = case when attempts >= 3 then 'failed' else 'pending' end,
      processing_started_at = null,
      last_error = left(p_error, 1000),
      updated_at = now()
  where id = p_event_id
    and recommendation is null;
$$;

revoke all on function public.detect_biggie_price_change() from public, anon, authenticated;
revoke all on function public.claim_price_change_event(bigint) from public, anon, authenticated;
revoke all on function public.complete_price_change_event(bigint, text, text) from public, anon, authenticated;
revoke all on function public.fail_price_change_event(bigint, text) from public, anon, authenticated;

grant execute on function public.claim_price_change_event(bigint) to service_role;
grant execute on function public.complete_price_change_event(bigint, text, text) to service_role;
grant execute on function public.fail_price_change_event(bigint, text) to service_role;
